language: "perl"
perl:
#   - "5.10"
#   - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
install: "echo"
before_script:
    - perl -S cpanm -n IPC::Run B::Flags Opcodes IO::Socket::SSL JSON::XS
    - perl -S cpanm -n LWP::UserAgent Net::SSLeay Net::LibIDN Net::IDN::Encode Net::DNS

script: "perl Makefile.PL && make && make testfast"

notifications:
  irc: "irc.perl.org#compiler"
  recipients:
    - perl-compiler@googlegroups.com
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - perl: "5.18"
    - perl: "5.20"
