--- #YAML:1.0
name:               B-C
version:            1.29
abstract:           Perl compiler
author:
    - Malcolm Beattie (retired), Reini Urban <perl-compiler@googlegroups.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Flags:     0.04
    IPC::Run:     0
    Opcodes:      0
    Time::HiRes:  0
resources:
    bugtracker:   http://code.google.com/p/perl-compiler/issues
    homepage:     http://www.perl-compiler.org
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/perl-compiler
    repository:   http://perl-compiler.googlecode.com/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    B::Debug:  1.16
    B::Flags:  0.04
    IPC::Run:  0
    Opcodes:   0.10
